Libraries

In [41]:
import pandas as pd
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from IPython.display import display

import requests

%pylab inline
import seaborn as sb
# pd.set_option('display.precision', 5)

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

In [42]:
# Importar Enero

df = []

for i in range(1, 32):
  url = f'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/refs/heads/master/csse_covid_19_data/csse_covid_19_daily_reports/01-{str(i).zfill(2)}-2021.csv'
  df.append(pd.read_csv(url))

In [43]:
# Combinar los DataFrames diarios en uno solo.

enero = pd.concat(df, ignore_index=True)

In [44]:
# Verificar

for i in df:
    display(i)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-02 05:22:33,33.93911,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,NaN,NaN,NaN,Albania,2021-01-02 05:22:33,41.15330,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,NaN,NaN,NaN,Algeria,2021-01-02 05:22:33,28.03390,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,NaN,NaN,NaN,Andorra,2021-01-02 05:22:33,42.50630,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,NaN,NaN,NaN,Angola,2021-01-02 05:22:33,-11.20270,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,NaN,NaN,Unknown,Ukraine,2021-01-02 05:22:33,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,NaN,NaN,NaN,Nauru,2021-01-02 05:22:33,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,NaN,NaN,Niue,New Zealand,2021-01-02 05:22:33,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,NaN,NaN,NaN,Tuvalu,2021-01-02 05:22:33,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-02 05:22:33,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-03 05:22:52,33.93911,67.709953,52586,2211,41727,8648,Afghanistan,135.084102,4.204541
1,NaN,NaN,NaN,Albania,2021-01-03 05:22:52,41.15330,20.168300,58991,1190,34353,23448,Albania,2049.864480,2.017257
2,NaN,NaN,NaN,Algeria,2021-01-03 05:22:52,28.03390,1.659600,100159,2769,67611,29779,Algeria,228.407338,2.764604
3,NaN,NaN,NaN,Andorra,2021-01-03 05:22:52,42.50630,1.521800,8166,84,7463,619,Andorra,10568.821588,1.028655
4,NaN,NaN,NaN,Angola,2021-01-03 05:22:52,-11.20270,17.873900,17608,407,11189,6012,Angola,53.574686,2.311449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,NaN,NaN,Unknown,Ukraine,2021-01-03 05:22:52,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,NaN,NaN,NaN,Nauru,2021-01-03 05:22:52,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,NaN,NaN,Niue,New Zealand,2021-01-03 05:22:52,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,NaN,NaN,NaN,Tuvalu,2021-01-03 05:22:52,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-03 05:22:52,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-04 05:22:02,33.93911,67.709953,52709,2221,41727,8761,Afghanistan,135.400068,4.213702
1,NaN,NaN,NaN,Albania,2021-01-04 05:22:02,41.15330,20.168300,59438,1193,34648,23597,Albania,2065.397178,2.007133
2,NaN,NaN,NaN,Algeria,2021-01-04 05:22:02,28.03390,1.659600,100408,2772,67808,29828,Algeria,228.975169,2.760736
3,NaN,NaN,NaN,Andorra,2021-01-04 05:22:02,42.50630,1.521800,8192,84,7517,591,Andorra,10602.472012,1.025391
4,NaN,NaN,NaN,Angola,2021-01-04 05:22:02,-11.20270,17.873900,17642,408,11223,6011,Angola,53.678136,2.312663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-04 05:22:02,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-04 05:22:02,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-04 05:22:02,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-04 05:22:02,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-04 05:22:02,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-05 05:21:49,33.93911,67.709953,52909,2230,42530,8149,Afghanistan,135.913832,4.214784
1,NaN,NaN,NaN,Albania,2021-01-05 05:21:49,41.15330,20.168300,59623,1199,34996,23428,Albania,2071.825700,2.010969
2,NaN,NaN,NaN,Algeria,2021-01-05 05:21:49,28.03390,1.659600,100645,2777,67999,29869,Algeria,229.515635,2.759203
3,NaN,NaN,NaN,Andorra,2021-01-05 05:21:49,42.50630,1.521800,8249,84,7548,617,Andorra,10676.244095,1.018305
4,NaN,NaN,NaN,Angola,2021-01-05 05:21:49,-11.20270,17.873900,17684,408,11266,6010,Angola,53.805926,2.307170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-05 05:21:49,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-05 05:21:49,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-05 05:21:49,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-05 05:21:49,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-05 05:21:49,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-06 05:22:16,33.93911,67.709953,53011,2237,42666,8108,Afghanistan,136.175852,4.219879
1,NaN,NaN,NaN,Albania,2021-01-06 05:22:16,41.15330,20.168300,60283,1210,35551,23522,Albania,2094.759886,2.007199
2,NaN,NaN,NaN,Algeria,2021-01-06 05:22:16,28.03390,1.659600,100873,2782,68185,29906,Algeria,230.035577,2.757923
3,NaN,NaN,NaN,Andorra,2021-01-06 05:22:16,42.50630,1.521800,8308,84,7585,639,Andorra,10752.604672,1.011074
4,NaN,NaN,NaN,Angola,2021-01-06 05:22:16,-11.20270,17.873900,17756,410,11376,5970,Angola,54.024996,2.309079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-06 05:22:16,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-06 05:22:16,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-06 05:22:16,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-06 05:22:16,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-06 05:22:16,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-07 05:22:03,33.93911,67.709953,53105,2244,42666,8195,Afghanistan,136.417321,4.225591
1,NaN,NaN,NaN,Albania,2021-01-07 05:22:03,41.15330,20.168300,61008,1217,36102,23689,Albania,2119.952742,1.994820
2,NaN,NaN,NaN,Algeria,2021-01-07 05:22:03,28.03390,1.659600,101120,2786,68383,29951,Algeria,230.598848,2.755142
3,NaN,NaN,NaN,Andorra,2021-01-07 05:22:03,42.50630,1.521800,8348,84,7615,649,Andorra,10804.374555,1.006229
4,NaN,NaN,NaN,Angola,2021-01-07 05:22:03,-11.20270,17.873900,17864,413,11477,5974,Angola,54.353600,2.311912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-07 05:22:03,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-07 05:22:03,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-07 05:22:03,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-07 05:22:03,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-07 05:22:03,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-08 05:22:42,33.93911,67.709953,53207,2253,43291,7663,Afghanistan,136.679341,4.234405
1,NaN,NaN,NaN,Albania,2021-01-08 05:22:42,41.15330,20.168300,61705,1223,36535,23947,Albania,2144.172632,1.982011
2,NaN,NaN,NaN,Algeria,2021-01-08 05:22:42,28.03390,1.659600,101382,2792,68589,30001,Algeria,231.196325,2.753941
3,NaN,NaN,NaN,Andorra,2021-01-08 05:22:42,42.50630,1.521800,8348,84,7615,649,Andorra,10804.374555,1.006229
4,NaN,NaN,NaN,Angola,2021-01-08 05:22:42,-11.20270,17.873900,17974,413,11955,5606,Angola,54.688290,2.297763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-08 05:22:42,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-08 05:22:42,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-08 05:22:42,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-08 05:22:42,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-08 05:22:42,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-09 05:22:18,33.93911,67.709953,53332,2257,43440,7635,Afghanistan,137.000444,4.231981
1,NaN,NaN,NaN,Albania,2021-01-09 05:22:18,41.15330,20.168300,62378,1230,36971,24177,Albania,2167.558552,1.971849
2,NaN,NaN,NaN,Algeria,2021-01-09 05:22:18,28.03390,1.659600,101657,2798,68802,30057,Algeria,231.823448,2.752393
3,NaN,NaN,NaN,Andorra,2021-01-09 05:22:18,42.50630,1.521800,8489,84,7724,681,Andorra,10986.863392,0.989516
4,NaN,NaN,NaN,Angola,2021-01-09 05:22:18,-11.20270,17.873900,18066,415,12712,4939,Angola,54.968212,2.297133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-09 05:22:18,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-09 05:22:18,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-09 05:22:18,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-09 05:22:18,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-09 05:22:18,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-10 05:22:12,33.93911,67.709953,53400,2264,43740,7396,Afghanistan,137.175124,4.239700
1,NaN,NaN,NaN,Albania,2021-01-10 05:22:12,41.15330,20.168300,63033,1233,37327,24473,Albania,2190.318994,1.956118
2,NaN,NaN,NaN,Algeria,2021-01-10 05:22:12,28.03390,1.659600,101913,2803,69011,30099,Algeria,232.407243,2.750385
3,NaN,NaN,NaN,Andorra,2021-01-10 05:22:12,42.50630,1.521800,8586,85,7724,777,Andorra,11112.405358,0.989984
4,NaN,NaN,NaN,Angola,2021-01-10 05:22:12,-11.20270,17.873900,18156,416,13205,4535,Angola,55.242049,2.291254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-10 05:22:12,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-10 05:22:12,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-10 05:22:12,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-10 05:22:12,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-10 05:22:12,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-11 05:21:50,33.93911,67.709953,53489,2277,43948,7264,Afghanistan,137.403749,4.256950
1,NaN,NaN,NaN,Albania,2021-01-11 05:21:50,41.15330,20.168300,63595,1241,37648,24706,Albania,2209.847800,1.951411
2,NaN,NaN,NaN,Algeria,2021-01-11 05:21:50,28.03390,1.659600,102144,2807,69212,30125,Algeria,232.934026,2.748081
3,NaN,NaN,NaN,Andorra,2021-01-11 05:21:50,42.50630,1.521800,8586,85,7724,777,Andorra,11112.405358,0.989984
4,NaN,NaN,NaN,Angola,2021-01-11 05:21:50,-11.20270,17.873900,18193,416,13872,3905,Angola,55.354627,2.286594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-11 05:21:50,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-11 05:21:50,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-11 05:21:50,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-11 05:21:50,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-11 05:21:50,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-12 05:22:15,33.93911,67.709953,53538,2288,44137,7113,Afghanistan,137.529621,4.273600
1,NaN,NaN,NaN,Albania,2021-01-12 05:22:15,41.15330,20.168300,63971,1247,37981,24743,Albania,2222.913337,1.949321
2,NaN,NaN,NaN,Algeria,2021-01-12 05:22:15,28.03390,1.659600,102369,2812,69403,30154,Algeria,233.447127,2.746925
3,NaN,NaN,NaN,Andorra,2021-01-12 05:22:15,42.50630,1.521800,8586,85,7724,777,Andorra,11112.405358,0.989984
4,NaN,NaN,NaN,Angola,2021-01-12 05:22:15,-11.20270,17.873900,18254,420,14825,3009,Angola,55.540227,2.300866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-12 05:22:15,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-12 05:22:15,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-12 05:22:15,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-12 05:22:15,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-12 05:22:15,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-13 05:22:15,33.93911,67.709953,53584,2301,44608,6675,Afghanistan,137.647787,4.294192
1,NaN,NaN,NaN,Albania,2021-01-13 05:22:15,41.15330,20.168300,64627,1252,38421,24954,Albania,2245.708527,1.937271
2,NaN,NaN,NaN,Algeria,2021-01-13 05:22:15,28.03390,1.659600,102641,2816,69608,30217,Algeria,234.067409,2.743543
3,NaN,NaN,NaN,Andorra,2021-01-13 05:22:15,42.50630,1.521800,8682,86,7930,666,Andorra,11236.653077,0.990555
4,NaN,NaN,NaN,Angola,2021-01-13 05:22:15,-11.20270,17.873900,18343,422,15512,2409,Angola,55.811022,2.300605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-13 05:22:15,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-13 05:22:15,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-13 05:22:15,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-13 05:22:15,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-13 05:22:15,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-14 05:22:32,33.93911,67.709953,53690,2308,44850,6532,Afghanistan,137.920082,4.298752
1,NaN,NaN,NaN,Albania,2021-01-14 05:22:32,41.15330,20.168300,65334,1256,38860,25218,Albania,2270.275905,1.922429
2,NaN,NaN,NaN,Algeria,2021-01-14 05:22:32,28.03390,1.659600,102860,2819,69791,30250,Algeria,234.566827,2.740618
3,NaN,NaN,NaN,Andorra,2021-01-14 05:22:32,42.50630,1.521800,8818,87,8070,661,Andorra,11412.670679,0.986618
4,NaN,NaN,NaN,Angola,2021-01-14 05:22:32,-11.20270,17.873900,18425,424,15631,2370,Angola,56.060518,2.301221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-14 05:22:32,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-14 05:22:32,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-14 05:22:32,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-14 05:22:32,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-14 05:22:32,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-15 05:22:24,33.93911,67.709953,53775,2314,45298,6163,Afghanistan,138.138432,4.303115
1,NaN,NaN,NaN,Albania,2021-01-15 05:22:24,41.15330,20.168300,65994,1261,39246,25487,Albania,2293.210091,1.910780
2,NaN,NaN,NaN,Algeria,2021-01-15 05:22:24,28.03390,1.659600,103127,2822,69992,30313,Algeria,235.175706,2.736432
3,NaN,NaN,NaN,Andorra,2021-01-15 05:22:24,42.50630,1.521800,8868,88,8091,689,Andorra,11477.383032,0.992332
4,NaN,NaN,NaN,Angola,2021-01-15 05:22:24,-11.20270,17.873900,18613,425,16008,2180,Angola,56.632533,2.283350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,Unknown,Ukraine,2021-01-15 05:22:24,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4008,NaN,NaN,NaN,Nauru,2021-01-15 05:22:24,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4009,NaN,NaN,Niue,New Zealand,2021-01-15 05:22:24,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4010,NaN,NaN,NaN,Tuvalu,2021-01-15 05:22:24,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4011,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-15 05:22:24,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-16 05:22:40,33.93911,67.709953,53831,2324,45434,6073,Afghanistan,138.282286,4.317215
1,NaN,NaN,NaN,Albania,2021-01-16 05:22:40,41.15330,20.168300,66635,1265,39625,25745,Albania,2315.484050,1.898402
2,NaN,NaN,NaN,Algeria,2021-01-16 05:22:40,28.03390,1.659600,103381,2827,70188,30366,Algeria,235.754940,2.734545
3,NaN,NaN,NaN,Andorra,2021-01-16 05:22:40,42.50630,1.521800,8946,88,8116,742,Andorra,11578.334304,0.983680
4,NaN,NaN,NaN,Angola,2021-01-16 05:22:40,-11.20270,17.873900,18679,428,16120,2131,Angola,56.833347,2.291343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4008,NaN,NaN,Unknown,Ukraine,2021-01-16 05:22:40,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4009,NaN,NaN,NaN,Nauru,2021-01-16 05:22:40,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4010,NaN,NaN,Niue,New Zealand,2021-01-16 05:22:40,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4011,NaN,NaN,NaN,Tuvalu,2021-01-16 05:22:40,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4012,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-16 05:22:40,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-17 05:22:17,33.93911,67.709953,53938,2336,45465,6137,Afghanistan,138.557150,4.330898
1,NaN,NaN,NaN,Albania,2021-01-17 05:22:17,41.15330,20.168300,67216,1270,40090,25856,Albania,2335.673084,1.889431
2,NaN,NaN,NaN,Algeria,2021-01-17 05:22:17,28.03390,1.659600,103611,2831,70373,30407,Algeria,236.279443,2.732335
3,NaN,NaN,NaN,Andorra,2021-01-17 05:22:17,42.50630,1.521800,9038,91,8116,831,Andorra,11697.405035,1.006860
4,NaN,NaN,NaN,Angola,2021-01-17 05:22:17,-11.20270,17.873900,18765,431,16225,2109,Angola,57.095013,2.296829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4008,NaN,NaN,Unknown,Ukraine,2021-01-17 05:22:17,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4009,NaN,NaN,NaN,Nauru,2021-01-17 05:22:17,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4010,NaN,NaN,Niue,New Zealand,2021-01-17 05:22:17,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4011,NaN,NaN,NaN,Tuvalu,2021-01-17 05:22:17,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4012,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-17 05:22:17,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-18 05:22:34,33.93911,67.709953,53984,2339,45868,5777,Afghanistan,138.675316,4.332765
1,NaN,NaN,NaN,Albania,2021-01-18 05:22:34,41.15330,20.168300,67690,1277,40453,25960,Albania,2352.143999,1.886542
2,NaN,NaN,NaN,Algeria,2021-01-18 05:22:34,28.03390,1.659600,103833,2836,70554,30443,Algeria,236.785702,2.731309
3,NaN,NaN,NaN,Andorra,2021-01-18 05:22:34,42.50630,1.521800,9083,91,8154,838,Andorra,11755.646153,1.001872
4,NaN,NaN,NaN,Angola,2021-01-18 05:22:34,-11.20270,17.873900,18875,436,16347,2092,Angola,57.429703,2.309934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4008,NaN,NaN,Unknown,Ukraine,2021-01-18 05:22:34,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4009,NaN,NaN,NaN,Nauru,2021-01-18 05:22:34,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4010,NaN,NaN,Niue,New Zealand,2021-01-18 05:22:34,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4011,NaN,NaN,NaN,Tuvalu,2021-01-18 05:22:34,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4012,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-18 05:22:34,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-19 05:22:15,33.93911,67.709953,54062,2343,46359,5360,Afghanistan,138.875684,4.333913
1,NaN,NaN,NaN,Albania,2021-01-19 05:22:15,41.15330,20.168300,67982,1281,40870,25831,Albania,2362.290639,1.884322
2,NaN,NaN,NaN,Algeria,2021-01-19 05:22:15,28.03390,1.659600,104092,2840,70747,30505,Algeria,237.376338,2.728356
3,NaN,NaN,NaN,Andorra,2021-01-19 05:22:15,42.50630,1.521800,9083,91,8154,838,Andorra,11755.646153,1.001872
4,NaN,NaN,NaN,Angola,2021-01-19 05:22:15,-11.20270,17.873900,18926,439,16677,1810,Angola,57.584877,2.319560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4008,NaN,NaN,Unknown,Ukraine,2021-01-19 05:22:15,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4009,NaN,NaN,NaN,Nauru,2021-01-19 05:22:15,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4010,NaN,NaN,Niue,New Zealand,2021-01-19 05:22:15,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4011,NaN,NaN,NaN,Tuvalu,2021-01-19 05:22:15,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4012,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-19 05:22:15,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-20 05:21:54,33.93911,67.709953,54141,2346,46554,5241,Afghanistan,139.078621,4.333130
1,NaN,NaN,NaN,Albania,2021-01-20 05:21:54,41.15330,20.168300,68568,1287,41464,25817,Albania,2382.653416,1.876969
2,NaN,NaN,NaN,Algeria,2021-01-20 05:21:54,28.03390,1.659600,104341,2843,70933,30565,Algeria,237.944169,2.724720
3,NaN,NaN,NaN,Andorra,2021-01-20 05:21:54,42.50630,1.521800,9194,92,8349,753,Andorra,11899.307578,1.000653
4,NaN,NaN,NaN,Angola,2021-01-20 05:21:54,-11.20270,17.873900,19011,442,16822,1747,Angola,57.843501,2.324970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4008,NaN,NaN,Unknown,Ukraine,2021-01-20 05:21:54,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4009,NaN,NaN,NaN,Nauru,2021-01-20 05:21:54,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4010,NaN,NaN,Niue,New Zealand,2021-01-20 05:21:54,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4011,NaN,NaN,NaN,Tuvalu,2021-01-20 05:21:54,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4012,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-20 05:21:54,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-21 05:22:01,33.93911,67.709953,54278,2354,46759,5165,Afghanistan,139.430550,4.336932
1,NaN,NaN,NaN,Albania,2021-01-21 05:22:01,41.15330,20.168300,69238,1291,41969,25978,Albania,2405.935089,1.864583
2,NaN,NaN,NaN,Algeria,2021-01-21 05:22:01,28.03390,1.659600,104606,2849,71127,30630,Algeria,238.548488,2.723553
3,NaN,NaN,NaN,Andorra,2021-01-21 05:22:01,42.50630,1.521800,9308,92,8399,817,Andorra,12046.851744,0.988397
4,NaN,NaN,NaN,Angola,2021-01-21 05:22:01,-11.20270,17.873900,19093,444,16921,1728,Angola,58.092997,2.325460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4008,NaN,NaN,Unknown,Ukraine,2021-01-21 05:22:01,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4009,NaN,NaN,NaN,Nauru,2021-01-21 05:22:01,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4010,NaN,NaN,Niue,New Zealand,2021-01-21 05:22:01,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4011,NaN,NaN,NaN,Tuvalu,2021-01-21 05:22:01,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4012,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-21 05:22:01,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-22 05:22:10,33.93911,67.709953,54403,2363,46887,5153,Afghanistan,139.751653,4.343510
1,NaN,NaN,NaN,Albania,2021-01-22 05:22:10,41.15330,20.168300,69916,1296,42426,26194,Albania,2429.494753,1.853653
2,NaN,NaN,NaN,Algeria,2021-01-22 05:22:10,28.03390,1.659600,104852,2853,71343,30656,Algeria,239.109478,2.720978
3,NaN,NaN,NaN,Andorra,2021-01-22 05:22:10,42.50630,1.521800,9379,93,8474,812,Andorra,12138.743286,0.991577
4,NaN,NaN,NaN,Angola,2021-01-22 05:22:10,-11.20270,17.873900,19177,448,17176,1553,Angola,58.348578,2.336132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-22 05:22:10,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-22 05:22:10,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-22 05:22:10,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-22 05:22:10,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-22 05:22:10,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-23 05:22:03,33.93911,67.709953,54483,2370,46912,5201,Afghanistan,139.957159,4.349981
1,NaN,NaN,NaN,Albania,2021-01-23 05:22:03,41.15330,20.168300,70655,1303,42895,26457,Albania,2455.174091,1.844172
2,NaN,NaN,NaN,Algeria,2021-01-23 05:22:03,28.03390,1.659600,105124,2856,71552,30716,Algeria,239.729760,2.716792
3,NaN,NaN,NaN,Andorra,2021-01-23 05:22:03,42.50630,1.521800,9416,93,8537,786,Andorra,12186.630428,0.987681
4,NaN,NaN,NaN,Angola,2021-01-23 05:22:03,-11.20270,17.873900,19269,452,17223,1594,Angola,58.628500,2.345737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-23 05:22:03,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-23 05:22:03,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-23 05:22:03,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-23 05:22:03,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-23 05:22:03,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-24 05:22:35,33.93911,67.709953,54559,2373,46943,5243,Afghanistan,140.152389,4.349420
1,NaN,NaN,NaN,Albania,2021-01-24 05:22:35,41.15330,20.168300,71441,1310,43384,26747,Albania,2482.486622,1.833681
2,NaN,NaN,NaN,Algeria,2021-01-24 05:22:35,28.03390,1.659600,105369,2861,71755,30753,Algeria,240.288469,2.715220
3,NaN,NaN,NaN,Andorra,2021-01-24 05:22:35,42.50630,1.521800,9499,96,8588,815,Andorra,12294.052935,1.010633
4,NaN,NaN,NaN,Angola,2021-01-24 05:22:35,-11.20270,17.873900,19367,457,17249,1661,Angola,58.926678,2.359684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-24 05:22:35,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-24 05:22:35,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-24 05:22:35,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-24 05:22:35,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-24 05:22:35,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-25 05:22:16,33.93911,67.709953,54595,2378,47298,4919,Afghanistan,140.244867,4.355710
1,NaN,NaN,NaN,Albania,2021-01-25 05:22:16,41.15330,20.168300,72274,1315,43890,27069,Albania,2511.432344,1.819465
2,NaN,NaN,NaN,Algeria,2021-01-25 05:22:16,28.03390,1.659600,105596,2863,71945,30788,Algeria,240.806131,2.711277
3,NaN,NaN,NaN,Andorra,2021-01-25 05:22:16,42.50630,1.521800,9549,96,8652,801,Andorra,12358.765288,1.005341
4,NaN,NaN,NaN,Angola,2021-01-25 05:22:16,-11.20270,17.873900,19399,459,17266,1674,Angola,59.024043,2.366101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-25 05:22:16,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-25 05:22:16,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-25 05:22:16,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-25 05:22:16,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-25 05:22:16,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-26 05:22:02,33.93911,67.709953,54672,2385,47365,4922,Afghanistan,140.442666,4.362379
1,NaN,NaN,NaN,Albania,2021-01-26 05:22:02,41.15330,20.168300,72812,1324,44291,27197,Albania,2530.127180,1.818382
2,NaN,NaN,NaN,Algeria,2021-01-26 05:22:02,28.03390,1.659600,105854,2866,72143,30845,Algeria,241.394486,2.707503
3,NaN,NaN,NaN,Andorra,2021-01-26 05:22:02,42.50630,1.521800,9596,97,8724,775,Andorra,12419.594901,1.010838
4,NaN,NaN,NaN,Angola,2021-01-26 05:22:02,-11.20270,17.873900,19476,461,17327,1688,Angola,59.258325,2.367016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-26 05:22:02,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-26 05:22:02,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-26 05:22:02,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-26 05:22:02,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-26 05:22:02,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-27 05:23:41,33.93911,67.709953,54750,2389,47459,4902,Afghanistan,140.643034,4.363470
1,NaN,NaN,NaN,Albania,2021-01-27 05:23:41,41.15330,20.168300,73691,1332,44880,27479,Albania,2560.671346,1.807548
2,NaN,NaN,NaN,Algeria,2021-01-27 05:23:41,28.03390,1.659600,106097,2871,72336,30890,Algeria,241.948635,2.706014
3,NaN,NaN,NaN,Andorra,2021-01-27 05:23:41,42.50630,1.521800,9638,97,8774,767,Andorra,12473.953278,1.006433
4,NaN,NaN,NaN,Angola,2021-01-27 05:23:41,-11.20270,17.873900,19553,462,17388,1703,Angola,59.492608,2.362809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-27 05:23:41,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-27 05:23:41,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-27 05:23:41,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-27 05:23:41,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-27 05:23:41,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-28 05:22:24,33.93911,67.709953,54854,2389,47549,4916,Afghanistan,140.910192,4.355197
1,NaN,NaN,NaN,Albania,2021-01-28 05:22:24,41.15330,20.168300,74567,1339,45383,27845,Albania,2591.111266,1.795701
2,NaN,NaN,NaN,Algeria,2021-01-28 05:22:24,28.03390,1.659600,106359,2877,72538,30944,Algeria,242.546112,2.704990
3,NaN,NaN,NaN,Andorra,2021-01-28 05:22:24,42.50630,1.521800,9716,98,8851,767,Andorra,12574.904549,1.008646
4,NaN,NaN,NaN,Angola,2021-01-28 05:22:24,-11.20270,17.873900,19580,462,17602,1516,Angola,59.574759,2.359551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-28 05:22:24,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-28 05:22:24,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-28 05:22:24,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-28 05:22:24,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-28 05:22:24,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-29 05:22:23,33.93911,67.709953,54891,2397,47583,4911,Afghanistan,141.005238,4.366836
1,NaN,NaN,NaN,Albania,2021-01-29 05:22:23,41.15330,20.168300,75454,1350,45906,28198,Albania,2621.933421,1.789170
2,NaN,NaN,NaN,Algeria,2021-01-29 05:22:23,28.03390,1.659600,106610,2881,72745,30984,Algeria,243.118505,2.702373
3,NaN,NaN,NaN,Andorra,2021-01-29 05:22:23,42.50630,1.521800,9779,100,8942,737,Andorra,12656.442115,1.022599
4,NaN,NaN,NaN,Angola,2021-01-29 05:22:23,-11.20270,17.873900,19672,464,17692,1516,Angola,59.854681,2.358682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-29 05:22:23,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-29 05:22:23,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-29 05:22:23,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-29 05:22:23,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-29 05:22:23,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-30 05:22:49,33.93911,67.709953,54939,2399,47606,4934,Afghanistan,141.128542,4.366661
1,NaN,NaN,NaN,Albania,2021-01-30 05:22:49,41.15330,20.168300,76350,1358,46420,28572,Albania,2653.068316,1.778651
2,NaN,NaN,NaN,Algeria,2021-01-30 05:22:49,28.03390,1.659600,106887,2884,72956,31047,Algeria,243.750189,2.698177
3,NaN,NaN,NaN,Andorra,2021-01-30 05:22:49,42.50630,1.521800,9837,100,8986,751,Andorra,12731.508445,1.016570
4,NaN,NaN,NaN,Angola,2021-01-30 05:22:49,-11.20270,17.873900,19723,464,17918,1341,Angola,60.009856,2.352583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-30 05:22:49,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-30 05:22:49,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-30 05:22:49,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-30 05:22:49,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-30 05:22:49,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-31 05:22:42,33.93911,67.709953,55008,2400,47609,4999,Afghanistan,141.305791,4.363002
1,NaN,NaN,NaN,Albania,2021-01-31 05:22:42,41.15330,20.168300,77251,1369,46927,28955,Albania,2684.376955,1.772145
2,NaN,NaN,NaN,Algeria,2021-01-31 05:22:42,28.03390,1.659600,107122,2888,73152,31082,Algeria,244.286094,2.695991
3,NaN,NaN,NaN,Andorra,2021-01-31 05:22:42,42.50630,1.521800,9885,101,9045,739,Andorra,12793.632304,1.021750
4,NaN,NaN,NaN,Angola,2021-01-31 05:22:42,-11.20270,17.873900,19782,464,18015,1303,Angola,60.189371,2.345567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-01-31 05:22:42,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-01-31 05:22:42,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-01-31 05:22:42,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-01-31 05:22:42,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-31 05:22:42,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-02-01 05:22:53,33.93911,67.709953,55023,2400,47679,4944,Afghanistan,141.344323,4.361812
1,NaN,NaN,NaN,Albania,2021-02-01 05:22:53,41.15330,20.168300,78127,1380,47424,29323,Albania,2714.816874,1.766355
2,NaN,NaN,NaN,Algeria,2021-02-01 05:22:53,28.03390,1.659600,107339,2891,73344,31104,Algeria,244.780951,2.693336
3,NaN,NaN,NaN,Andorra,2021-02-01 05:22:53,42.50630,1.521800,9937,101,9093,743,Andorra,12860.933152,1.016403
4,NaN,NaN,NaN,Angola,2021-02-01 05:22:53,-11.20270,17.873900,19796,466,18035,1295,Angola,60.231968,2.354011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009,NaN,NaN,Unknown,Ukraine,2021-02-01 05:22:53,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4010,NaN,NaN,NaN,Nauru,2021-02-01 05:22:53,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4011,NaN,NaN,Niue,New Zealand,2021-02-01 05:22:53,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4012,NaN,NaN,NaN,Tuvalu,2021-02-01 05:22:53,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4013,NaN,NaN,Pitcairn Islands,United Kingdom,2021-02-01 05:22:53,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

In [45]:
# 1. Cargar y visualizar los primeros 5 registros del archivo 01-22-2020.csv

df[0].head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-02 05:22:33,33.93911,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,NaN,NaN,NaN,Albania,2021-01-02 05:22:33,41.15330,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,NaN,NaN,NaN,Algeria,2021-01-02 05:22:33,28.03390,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,NaN,NaN,NaN,Andorra,2021-01-02 05:22:33,42.50630,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,NaN,NaN,NaN,Angola,2021-01-02 05:22:33,-11.20270,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328

In [46]:
# 2. Mostrar el número total de filas y columnas del DataFrame.

print('Filas en total: ', len(enero))
print('Columnas en total: ', len(enero.columns))

Filas en total:  124398
Columnas en total:  14

In [47]:
# 3. Describir los tipos de datos (dtypes) y convertir las columnas necesarias (por ejemplo,
# fechas).

enero.dtypes

FIPS                   float64
Admin2                  object
Province_State          object
Country_Region          object
Last_Update             object
Lat                    float64
Long_                  float64
Confirmed                int64
Deaths                   int64
Recovered                int64
Active                   int64
Combined_Key            object
Incident_Rate          float64
Case_Fatality_Ratio    float64
dtype: object

In [48]:
# 3

enero['Last_Update'] = pd.to_datetime(enero['Last_Update'], format = 'ISO8601')

enero.dtypes

FIPS                          float64
Admin2                         object
Province_State                 object
Country_Region                 object
Last_Update            datetime64[ns]
Lat                           float64
Long_                         float64
Confirmed                       int64
Deaths                          int64
Recovered                       int64
Active                          int64
Combined_Key                   object
Incident_Rate                 float64
Case_Fatality_Ratio           float64
dtype: object

In [49]:
# 4. Detectar y mostrar valores nulos o faltantes por columna.

display(enero.isnull().sum())

FIPS                   23166
Admin2                 23011
Province_State          5529
Country_Region             0
Last_Update                0
Lat                     2776
Long_                   2776
Confirmed                  0
Deaths                     0
Recovered                  0
Active                     0
Combined_Key               0
Incident_Rate           2776
Case_Fatality_Ratio     1484
dtype: int64

In [50]:
# 5. Eliminar columnas irrelevantes (por ejemplo, códigos FIPS o coordenadas si no se usarán).

enero = enero.drop(columns=['FIPS', 'Admin2', 'Lat', 'Long_', 'Combined_Key'])
enero.head(1)

,Province_State,Country_Region,Last_Update,Confirmed,Deaths,Recovered,Active,Incident_Rate,Case_Fatality_Ratio
0,NaN,Afghanistan,2021-01-02 05:22:33,52513,2201,41727,8585,134.896578,4.191343

In [51]:
# 6. Estandarizar nombres de columnas (usar formato snake_case).

enero.columns = enero.columns.str.lower().str.replace(' ', '_')
enero.head(1)

,province_state,country_region,last_update,confirmed,deaths,recovered,active,incident_rate,case_fatality_ratio
0,NaN,Afghanistan,2021-01-02 05:22:33,52513,2201,41727,8585,134.896578,4.191343

In [52]:
# 7. Homogeneizar nombres de países (ej. “US” → “United States”).

enero['country_region'] = enero['country_region'].replace({'US': 'United States'})
enero[enero['country_region'] == 'United States'].head(1)

,province_state,country_region,last_update,confirmed,deaths,recovered,active,incident_rate,case_fatality_ratio
648,Alabama,United States,2021-01-02 05:22:33,4239,50,0,4189,7587.391935,1.179523

In [53]:
# 8. Convertir la columna Last_Update al formato YYYY-MM-DD.

enero['last_update'] = pd.to_datetime(enero['last_update'], format='%Y-%M-%D') 
enero.head(1)

,province_state,country_region,last_update,confirmed,deaths,recovered,active,incident_rate,case_fatality_ratio
0,NaN,Afghanistan,2021-01-02 05:22:33,52513,2201,41727,8585,134.896578,4.191343

In [54]:
# 9. Crear una columna active_cases = Confirmed - Deaths - Recovered.

enero['active_cases'] = (enero['confirmed'] - enero['deaths'] - enero['recovered'])
enero.head(1)

,province_state,country_region,last_update,confirmed,deaths,recovered,active,incident_rate,case_fatality_ratio,active_cases
0,NaN,Afghanistan,2021-01-02 05:22:33,52513,2201,41727,8585,134.896578,4.191343,8585

In [55]:
# 10. Guardar el DataFrame limpio como covid_clean_enero2020.csv e indicar su tamaño en MB.

enero.to_csv('covid_clean_enero2020.csv')

In [59]:
# 10

import os

file_size = os.path.getsize('covid_clean_enero2020.csv') / (1024 * 1024)  # Convertir a MB
print(f'El tamaño del archivo covid_clean_enero2020.csv es: {file_size:.2f} MB')

El tamaño del archivo covid_clean_enero2020.csv es: 12.27 MB